version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9090:9090"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "9091:9091"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:9090
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge