version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9090:9090"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "9091:9091"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./local_docs:/app/docs
    depends_on:
      - backend
    env_file:
      - ./frontend/.env