version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9090:9090"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_volume:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  ollama_volume: