services:
  backend:
    build: ./backend
    ports:
      - "9090:9090"
    volumes:
      - chroma_db:/app/chroma_db
      - textracted:/app/textracted
      - uploads:/app/uploads
      - ./backend/src:/app/src
      - ./backend/secrets:/app/secrets
      - nltk_data:/home/appuser/nltk_data
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_APP=src.main
      - FLASK_RUN_PORT=9090
      - CHROMA_DB_PATH=/app/chroma_db
      - RAW_DOCUMENTS_PATH=/app/raw-documents
      - UPLOAD_FOLDER=/app/uploads
      - OLLAMA_HOST=host.docker.internal:11434
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - REDIS_URL=redis://redis
      - PYTHONPATH=/app/src
      - NLTK_DATA=/home/appuser/nltk_data
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      redis:
        condition: service_healthy
      chromadb:
        condition: service_healthy
    networks:
      - net

  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    networks:
      - net

  chromadb:
    image: chromadb/chroma:0.5.11
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 5s
      timeout: 30s
      retries: 50
    networks:
      - net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9091:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:9090
    depends_on:
      - backend
    networks:
      - net

networks:
  net:

volumes:
  chroma_db:
  textracted:
  uploads:
  chromadb_data:
  nltk_data:
