version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9090:9090"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    depends_on:
      ollama:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "9091:9091"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
  
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
    
volumes:
  ollama_data: